In [2]:
import numpy as np

## Datatypes and Attribuites

In [3]:
a1 =  np.array([1,2,3])

In [4]:
a2 = np.array([[1,2,3.4],
               [4,5,6]])

In [5]:
a3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[1,2,3], [5,5,5]]
])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 5,  5,  5]]])

In [7]:
a3.shape

(3, 2, 3)

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a2.dtype

dtype('float64')

In [12]:
a1.size

3

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# create dataframe from nmpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.4
1  4.0  5.0  6.0

## Creating arrays


In [16]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
zeros = np.zeros((3,4), int)
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0,50, size =(2,2,3))
random_array

array([[[37,  9, 42],
        [19, 47, 24]],

       [[21, 19, 29],
        [15,  0,  8]]])

In [21]:
random_array2 = np.random.random((2,3))
random_array2

array([[0.16419916, 0.08599025, 0.35618294],
       [0.55755715, 0.4102627 , 0.47676677]])

In [22]:
random_array3 = np.random.rand(2,3)
random_array3

array([[0.19284935, 0.08197432, 0.75147188],
       [0.52290124, 0.51212467, 0.82597254]])

In [23]:
random_array4 = np.random.rand(1,2,3)
random_array4

array([[[0.15093123, 0.63151508, 0.75690139],
        [0.86029693, 0.87868454, 0.4972291 ]]])

In [24]:
# psudo random number
np.random.seed(0)
ar = np.random.randint(0,9,(5,5))
ar

array([[5, 0, 3, 3, 7],
       [3, 5, 2, 4, 7],
       [6, 8, 8, 1, 6],
       [7, 7, 8, 1, 5],
       [8, 4, 3, 0, 3]])

## Viewing arrays and matrixes

In [25]:
np.unique([1,2,3,4,2,1,1,3,5])

array([1, 2, 3, 4, 5])

In [26]:
a1,a2,a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.4],
        [4. , 5. , 6. ]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[ 1,  2,  3],
         [ 5,  5,  5]]]))

In [27]:
a1[0]

1

In [28]:
a2[0]

array([1. , 2. , 3.4])

In [29]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 5,  5,  5]]])

In [31]:
a3[:2, :1, :2]

array([[[1, 2]],

       [[7, 8]]])

In [32]:
a4 = np.random.randint(10,size=(2,3,4,6))
a4

array([[[[5, 0, 2, 3, 8, 1],
         [3, 3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7, 3],
         [2, 7, 2, 0, 0, 4]],

        [[5, 5, 6, 8, 4, 1],
         [4, 9, 8, 1, 1, 7],
         [9, 9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4, 4]],

        [[6, 4, 4, 3, 4, 4],
         [8, 4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3, 0],
         [5, 0, 1, 2, 4, 2]]],


       [[[0, 3, 2, 0, 7, 5],
         [9, 0, 2, 7, 2, 9],
         [2, 3, 3, 2, 3, 4],
         [1, 2, 9, 1, 4, 6]],

        [[8, 2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8, 8],
         [8, 2, 3, 2, 0, 8],
         [8, 3, 8, 2, 8, 4]],

        [[3, 0, 4, 3, 6, 9],
         [8, 0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1, 8],
         [0, 4, 9, 6, 5, 7]]]])

In [33]:
a4[:1,:2,:2,:2]

array([[[[5, 0],
         [3, 3]],

        [[5, 5],
         [4, 9]]]])

## Manipulating comparing

### Arithmetic

In [34]:
one = np.ones(3)

In [35]:
a1+one

array([2., 3., 4.])

In [36]:
a1-one

array([0., 1., 2.])

In [37]:
a1

array([1, 2, 3])

In [38]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6. ]])

In [39]:
a1*a2

array([[ 1. ,  4. , 10.2],
       [ 4. , 10. , 18. ]])

### Aggregation

In [40]:
massive_array = np.random.random(100000)

In [41]:
%timeit sum(massive_array)

6.03 ms ± 120 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [42]:
%timeit np.sum(massive_array)

30.2 µs ± 766 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [43]:
np.mean(a2)

3.5666666666666664

In [44]:
np.min(a2)

1.0

In [45]:
np.max(a2)

6.0

In [46]:
np.std(a2)

1.6947631758514883

In [47]:
np.var(a2)

2.8722222222222222

### std and var

In [48]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6. ]])

In [49]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 5,  5,  5]]])

In [50]:
a2.shape, a3.shape

((2, 3), (3, 2, 3))

In [51]:
a3*a2

array([[[ 1. ,  4. , 10.2],
        [16. , 25. , 36. ]],

       [[ 7. , 16. , 30.6],
        [40. , 55. , 72. ]],

       [[ 1. ,  4. , 10.2],
        [20. , 25. , 30. ]]])

In [52]:
a5 = np.array([[[1,2,3],[3,4,5]],
               [[1,2,3],[3,4,5]]])

In [53]:
a5.shape

(2, 2, 3)

In [54]:
a5.ndim

3

In [55]:
np.std(a5)

1.2909944487358056

In [56]:
np.var(a5)

1.6666666666666667

### Reshape & Transpose

In [57]:
a5.shape

(2, 2, 3)

In [58]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6. ]])

In [59]:
a5 * a2

array([[[ 1. ,  4. , 10.2],
        [12. , 20. , 30. ]],

       [[ 1. ,  4. , 10.2],
        [12. , 20. , 30. ]]])

In [60]:
a2*a5

array([[[ 1. ,  4. , 10.2],
        [12. , 20. , 30. ]],

       [[ 1. ,  4. , 10.2],
        [12. , 20. , 30. ]]])

In [61]:
a5

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]])

### Image to numpy

<img src="image/nebula.jpg"/>

In [71]:
from matplotlib.image import imread

In [83]:
nebula = imread("image/nebula.jpg")

In [84]:
type(nebula)

numpy.ndarray

In [85]:
nebula.size

44236800

In [86]:
nebula.shape

(2880, 5120, 3)

In [87]:
nebula.std()

57.30865949834314

In [88]:
nebula.var()

3284.282453497035

In [90]:
nebula.mean()

65.34748035572193